<?php
##########################################################################################
#
#  project           	: Krecipes WebFrontend
#  filename          	: lang_en.php.php
#  last modified by  	: Nils Kristian Tomren
#  e-mail            	: project@nilsk.net
#  purpose           	: English Language File
#  last modified     	: 10.12.2005
#
##########################################################################################

$lng_metatag = "<meta http-equiv=\"Content-Type\" content=\"text/html;
charset=iso-8859-15\" />";

#index.php
$lng_index_catlist = "Category Listing";

#footer.php
$lng_frontend_ver = "Krecipes Web Frontend version";
$lng_gen_by = "Recipes generated by Krecipes.";

#view_cat.php
$lng_cat_cat = "Category";
$lng_cat_recipes = "Recipes";
$lng_cat_subc = "Subcategories";

#view_recipe.php/print_recipe.php
$lng_recipe_author = "Author";
$lng_recipe_yield = "Yield";
$lng_recipe_prep = "Prep time";
$lng_recipe_cat = "Categories";
$lng_cat_ingred = "Ingredients";
$lng_cat_instr = "Instructions";
$lng_print = "Print Recipe";
$lng_pfrom = "This recipe is printed from:";
$lng_sendfriend = "Send to a friend";
$lng_error = "Error";
$lng_ok = "Success";
$lng_error_friend_fmail = "Sorry, the e-mail address
you entered for your friend is invalid.<br /> Please try again, making certain
you have entered it correctly.";
$lng_error_friend_smail = "Sorry, the e-mail address you entered for yourself
is invalid.<br /> Please try again, making certain
you have entered it correctly.";
$lng_error_friend_name = "Sorry, you have to fill both your own and your
friends name.<br />";
$lng_send_friend_ok = "E-mail sent successfully to your friend.";

#view_recip_functions.php
$no_exist_recipe = "Recipe does not exist.";
$no_author = "No Authors";
$no_cat = "No Categories";

#view_recipe_bbox.php
$lng_yourn="Your name";
$lng_yourm="Your e-mail";
$lng_yourfn="Your friends name";
$lng_yourfm="Your friends e-mail";
$lng_pfunctions="Page Functions";


#menu.php
$lng_menu_catlist = "Category Listing";
$lng_menu_search ="Search";

#search.php
$lng_rec_search = "Recipe Search";
$lng_title = "Title";
$lng_yields = "Yields";
$lng_exactly = "exactly";
$lng_atleast = "at least";
$lng_atmost = "at most";
$lng_anycat = "In any of the following categories";
$lng_intext = "Instructions contains the text";
$lng_submit = "Submit";
$lng_reset = "Clear form";

#search_results.php
$lng_sres = "Search Results";
$lng_rsres = "Recipe Search Results";
$lng_res = "Results";
$lng_nores = "No recipes found.";

#send_friend.php
$lng_wishes="Regards";
$lng_subject="A recipe for you from ";
$lng_message1_1="Your friend ";
$lng_message1_2=" have sent you a link to";
$lng_message2="a recipe at ";
$lng_message3="Visit the link below to see the recipe";
$lng_message4="Sent from";
$lng_from="From";
$lng_error55="The recipe id was not found!<br />Failed to send!";

# Error messages
$no_db_listings = "No listings in Krecipes database!";
$no_recipe_chosen = "No recipe chosen";
$no_cat_listings ="No listings in this category";
?>